<h1>Project-Facial Recognization

<h5>1 Import the required libraries:

<h6>We'll begin by importing the necessary libraries for the project:
In this step, we import the necessary Python libraries to work with our project. We import numpy for handling numerical data in arrays, tensorflow for building and training machine learning models, and keras as a high-level neural networks API built on top of TensorFlow.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


<h5>2 Load the datasets:
<h6>Load the training and testing datasets from the provided files:
We load the training and testing datasets from the provided files using the np.load() function from NumPy. The data is loaded into train_images, train_labels, test_images, and test_labels variables.

In [2]:
train_images = np.load(f'./facial_data/train_images.npy')
train_labels = np.load(f'./facial_data/train_labels.npy')
test_images =  np.load(f'./facial_data/test_images.npy')
test_labels =  np.load(f'./facial_data/test_labels.npy')


<h5>3 Preprocess the data:
<h6>Preprocess the data by normalizing the pixel values and converting labels to one-hot encoded format:
In this step, we preprocess the data to prepare it for training the model. We normalize the pixel values of the images to be in the range [0, 1] by dividing them by 255.0, as the original pixel values are integers ranging from 0 to 255. Additionally, we adjust the labels to start from 0 by subtracting 1 from all label values. Then, we convert the labels to one-hot encoded format using keras.utils.to_categorical(). This step is necessary for training the neural network, as it converts the labels into a binary matrix representation suitable for multi-class classification.

In [3]:
# Normalize pixel values to range [0, 1]
train_images = train_images.astype('float32') / 255.0
test_images = test_images.astype('float32') / 255.0

# Adjust labels to start from 0 (subtract 1 from all label values)
train_labels = train_labels - 1
test_labels = test_labels - 1

# Check the unique labels in the training dataset
unique_labels_train = np.unique(train_labels)
print("Unique labels in training data:", unique_labels_train)

# Check the unique labels in the testing dataset
unique_labels_test = np.unique(test_labels)
print("Unique labels in testing data:", unique_labels_test)

# Convert labels to one-hot encoded format
num_classes = len(np.unique(train_labels))
train_labels = keras.utils.to_categorical(train_labels, num_classes)
test_labels = keras.utils.to_categorical(test_labels, num_classes)


Unique labels in training data: [0 1 2 3 4 5 6]
Unique labels in testing data: [0 1 2 3 4 5 6]


<h5>4 Build the ConvNet model:
<h6>Build a Convolutional Neural Network model using Keras:
In this step, we build the Convolutional Neural Network (ConvNet) model using Keras. A ConvNet is a type of neural network particularly effective for computer vision tasks, as it can automatically learn hierarchical patterns and features from images. The model architecture consists of multiple Conv2D layers with ReLU activation for feature extraction, followed by MaxPooling2D layers for downsampling, and finally, Dense layers for classification.

In [4]:
# Determine the image size from the data
image_height, image_width = train_images.shape[1], train_images.shape[2]
print("Image height:", image_height)
print("Image width:", image_width)

# Build the ConvNet model
model = keras.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(image_height, image_width, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.summary()



Image height: 48
Image width: 48
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 46, 46, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2  (None, 23, 23, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 21, 21, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 10, 10, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 8, 8, 128)         73856     
                                                                 
 flatten (Flatten)     

<h5>5 Compile the model:
<h6>Compile the model with an appropriate optimizer and loss function:
After building the model, we need to compile it before training. Compiling the model involves specifying the optimizer, loss function, and evaluation metrics. In this case, we use the "adam" optimizer, which is an adaptive learning rate optimization algorithm, the "categorical_crossentropy" loss function, suitable for multi-class classification problems, and we track the "accuracy" metric during training to monitor the model's performance.

In [5]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


<h5>6 Train the model:
<h6>Train the model on the training data:
In this step, we train the model on the preprocessed training data using the model.fit() function. We specify the batch size (the number of samples per gradient update) and the number of epochs (the number of times the entire dataset will be passed through the network during training). The model is trained to learn the patterns and features in the images and make accurate predictions.

In [6]:
batch_size = 64
epochs = 2

model.fit(train_images, train_labels, batch_size=batch_size, epochs=epochs, validation_split=0.1)


Epoch 1/2
404/404 [==============================] - 125s 302ms/step - loss: 1.5995 - accuracy: 0.3441 - val_loss: 4.2837 - val_accuracy: 0.0000e+00
Epoch 2/2
404/404 [==============================] - 132s 325ms/step - loss: 1.3882 - accuracy: 0.4585 - val_loss: 4.0445 - val_accuracy: 0.0000e+00


<h5>7 Evaluate the model:
<h6>Evaluate the model on the test data:
Once the model is trained, we evaluate its performance on the test data using the model.evaluate() function. This step computes the loss and accuracy of the model on the unseen test data to assess its generalization and ability to make accurate predictions on new, unseen samples.

In [7]:
test_loss, test_accuracy = model.evaluate(test_images, test_labels, verbose=0)
print(f'Test accuracy: {test_accuracy}')


Test accuracy: 0.4352187216281891


<h5>8 Make predictions:
<h6>You can use the trained model to make predictions on new images:
After training and evaluation, we can use the trained model to make predictions on new images using the model.predict() function. The model takes the input images and outputs the predicted probabilities for each class label. The class label with the highest probability is considered the final prediction for the image.

In [9]:
predictions = model.predict(test_images)

225/225 [==============================] - 15s 64ms/step
[[0.26512077 0.03187996 0.27766496 ... 0.01653384 0.23267281 0.00413744]
 [0.32122222 0.01826053 0.26650032 ... 0.07093739 0.22788034 0.00406726]
 [0.43942636 0.04430061 0.24991037 ... 0.04836881 0.12296793 0.01260502]
 ...
 [0.29490873 0.03356543 0.3738431  ... 0.02188653 0.05044347 0.01776687]
 [0.05189067 0.00460207 0.36563796 ... 0.34553158 0.16967703 0.04566986]
 [0.03638849 0.01263612 0.17500986 ... 0.4580842  0.07110635 0.01836206]]


In [15]:
print(f"Accuracy = {tru/(tru+fls)}%")

Accuracy = 0.5154639175257731%
